### ISSUE TITLE
我在哪儿可以找到关于Piston的教程？

### ISSUE THREAD

**Issue by 3442853561** [PistonDevelopers/docs#8]
Is there any E-book for how to learn Piston?May I translate it into Chinese?

**Comment by echochamber** [comment]
There's not really a book in the same vein as _The Rust Programming Language_ that I am aware of. Just a lot of examples and then the docs themselves. If you are trying to use/learn piston and find any areas that you have difficulty figuring out please give feedback so that the docs/examples can improved on that section :).

On translating, I believe @bvssvni would be best to answer that question.

**Comment by bvssvni** [comment]
Translating would be great, even though there is not much to translate yet. I guess waiting with writing a book will save us some work for now (less maintenance). I have been thinking about this since I learned how to create one by working on the [Dyon tutorial](http://www.piston.rs/dyon-tutorial/introduction.html).

**Comment by 3442853561** [comment]
The documents of the Chinese version  already translated. 
https://3442853561.github.io/pistondoc/
